### ISSUE TITLE
Listing cases points to wrong URL

### ISSUE THREAD

**Issue by stolpeo** [varfish-org/varfish-cli#39]
**Describe the bug**
Listing cases of a project results in a 404.

**To Reproduce**
1. list cases of a project
4. see error

**Expected behavior**
Display list of cases instead of 404.

**Additional context**
```
$ varfish-cli case list aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
[I 230403 16:39:32] Configuration: CaseListConfig(case_config=CaseConfig(global_config=CommonConfig(verbose=False, verify_ssl=True, varfish_api_token='****************************************************************', varfish_server_url='https://varfish.bihealth.org/'), output_file='-', output_format=<OutputFormat.TABLE: 'table'>, output_delimiter=',', output_fields=('sodar_uuid', 'name', 'index', 'members')), project_uuid=UUID('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'))
[I 230403 16:39:32] Listing cases
Traceback (most recent call last):
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/bin/varfish-cli", line 10, in <module>
    sys.exit(main())
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/lib/python3.8/site-packages/varfish_cli/__main__.py", line 112, in main
    res = cmds[args.cmd](
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/lib/python3.8/site-packages/varfish_cli/case/__init__.py", line 94, in run
    return args.case_cmd(config, toml_config, args, parser, subparser)
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/lib/python3.8/site-packages/varfish_cli/case/list_case.py", line 39, in run
    res = api.case_list(
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/lib/python3.8/site-packages/varfish_cli/api/case.py", line 142, in case_list
    result.raise_for_status()
  File "/home/stolpeo/dev/miniconda3/envs/varfish-cli/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://varfish.bihealth.org/variants/api/case/list/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/
```

Might be an VarFish issue instead.

**Comment by stolpeo** [comment]
Duplicate of #27
